export default [
  { id: 1, on: true },
  { id: 2, on: true },
  { id: 3, on: false },
  { id: 4, on: false },
  { id: 5, on: false },
  { id: 6, on: true },
  { id: 7, on: true },
  { id: 8, on: true },
  { id: 9, on: false },
  { id: 10, on: false },
  { id: 11, on: false },
  { id: 12, on: true },
  { id: 13, on: true },
  { id: 14, on: true },
  { id: 15, on: false },
  { id: 16, on: false },
  { id: 17, on: false },
  { id: 18, on: true },
]
